/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Risfianoor
 */
public class ApkPenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ApkPenampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonpanel = new javax.swing.JPanel();
        WP1 = new javax.swing.JButton();
        WP2 = new javax.swing.JButton();
        WP3 = new javax.swing.JButton();
        BTEXIT = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        WPG1 = new javax.swing.JLabel();
        WPG2 = new javax.swing.JLabel();
        WPG3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonpanel.setBackground(new java.awt.Color(102, 102, 102));

        WP1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        WP1.setText("Wallpeaper 1");
        WP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WP1ActionPerformed(evt);
            }
        });
        buttonpanel.add(WP1);

        WP2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        WP2.setText("Wallpeaper 2");
        WP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WP2ActionPerformed(evt);
            }
        });
        buttonpanel.add(WP2);

        WP3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        WP3.setText("Wallpeaper 3");
        WP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WP3ActionPerformed(evt);
            }
        });
        buttonpanel.add(WP3);

        BTEXIT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTEXIT.setText("Exit");
        BTEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEXITActionPerformed(evt);
            }
        });
        buttonpanel.add(BTEXIT);

        imagepanel.setLayout(new java.awt.CardLayout());

        WPG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WPG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/WP1.jpg"))); // NOI18N
        WPG1.setToolTipText("");
        WPG1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagepanel.add(WPG1, "1");

        WPG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WPG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/WP2.jpg"))); // NOI18N
        WPG2.setToolTipText("");
        WPG2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagepanel.add(WPG2, "2");

        WPG3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WPG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/WP3.jpg"))); // NOI18N
        WPG3.setToolTipText("");
        WPG3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagepanel.add(WPG3, "3");

        buttonpanel.add(imagepanel);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WP1ActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, "1");
    }//GEN-LAST:event_WP1ActionPerformed

    private void WP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WP2ActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, "2");
    }//GEN-LAST:event_WP2ActionPerformed

    private void WP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WP3ActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, "3");
    }//GEN-LAST:event_WP3ActionPerformed

    private void BTEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTEXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApkPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApkPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApkPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApkPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApkPenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEXIT;
    private javax.swing.JButton WP1;
    private javax.swing.JButton WP2;
    private javax.swing.JButton WP3;
    private javax.swing.JLabel WPG1;
    private javax.swing.JLabel WPG2;
    private javax.swing.JLabel WPG3;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JPanel imagepanel;
    // End of variables declaration//GEN-END:variables
}
